version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Tehran
    open-pull-requests-limit: 5
    groups:
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - go

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Asia/Tehran
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Asia/Tehran
    open-pull-requests-limit: 3
    groups:
      docker-images:
        patterns:
          - "*"
    labels:
      - dependencies
      - docker
